FROM adoptopenjdk:8-jre-hotspot


RUN ln -s /usr/lib/libfontconfig.so.1 /usr/lib/libfontconfig.so && \
    ln -s /lib/libuuid.so.1 /usr/lib/libuuid.so.1 && \
    ln -s /lib/libc.musl-x86_64.so.1 /usr/lib/libc.musl-x86_64.so.1
ENV LD_LIBRARY_PATH /usr/lib

COPY ./*.jar app.jar
EXPOSE 8080

CMD java -Xmx100m -jar /app.jar
